apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.telegram: |
    token: $telegram-token
  subscriptions: |
    - recipients:
      - telegram:-1001517027225
      triggers:
      - on-created
      - on-deleted
      - on-deployed
      - on-sync-running
      - on-sync-failed
      - on-sync-status-unknown
      - on-sync-succeeded
