apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    name: guestbook
    namespace: apps
    server: https://kubernetes.default.svc
  source:
    path: apps/guestbook
    repoURL: https://github.com/sneils/gitops-demo
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
