apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  destination:
    name:
    namespace: nginx
    server: https://kubernetes.default.svc
  source:
    path: apps/nginx
    repoURL: https://github.com/sneils/gitops-demo
    targetRevision: demo
    directory:
      recurse: true
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
